server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/todo_app

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mvc:
    format:
      date-time: dd/MM/yyyy hh:mm

